import {randomUUID} from "node:crypto";import {readJson,ok,fail} from "./http.js";import {MemoryStore} from "./store.js";import {IdempotencyStore} from "./idempotency.js";
export function createHandler(store=new MemoryStore(),idem=new IdempotencyStore()){return async(req,res)=>{const id=String(req.headers["x-request-id"]||randomUUID());try{const u=new URL(req.url,"http://localhost");
if(req.method==="GET"&&u.pathname==="/health")return ok(res,{status:"ok",service:"smart-english-api"},id);
if(req.method==="POST"&&u.pathname==="/api/v1/auth/wechat/login"){const b=await readJson(req);if(!b.open_id)return fail(res,400,"AUTH_OPEN_ID_REQUIRED","open_id is required",id);const x=store.loginWechat(String(b.open_id));return ok(res,{user_id:x.user_id,status:x.status},id);}
if(req.method==="GET"&&u.pathname==="/api/v1/curriculum/textbooks")return ok(res,store.listTextbooks(Object.fromEntries(u.searchParams)),id);
let m=u.pathname.match(/^\/api\/v1\/curriculum\/textbooks\/([^/]+)\/structure$/);if(req.method==="GET"&&m){const x=store.getStructure(m[1]);return x?ok(res,x,id):fail(res,404,"CURRICULUM_TEXTBOOK_NOT_FOUND","textbook not found",id);}
if(req.method==="POST"&&u.pathname==="/api/v1/students"){const b=await readJson(req),uid=req.headers["x-user-id"];if(!uid)return fail(res,401,"AUTH_REQUIRED","x-user-id is required",id);if(!b.display_name||!b.current_stage||!Number.isInteger(b.current_grade))return fail(res,400,"STUDENT_INVALID_INPUT","display_name, current_stage and integer current_grade are required",id);if(!["Primary","Middle","High"].includes(b.current_stage)||b.current_grade<1||b.current_grade>12)return fail(res,400,"STUDENT_INVALID_GRADE","invalid stage or grade",id);return ok(res,store.createStudent(String(uid),b),id,201);}
m=u.pathname.match(/^\/api\/v1\/students\/([^/]+)\/config$/);if(req.method==="PATCH"&&m){const uid=req.headers["x-user-id"];if(!store.owns(String(uid),m[1]))return fail(res,403,"STUDENT_FORBIDDEN","student is not bound to user",id);const b=await readJson(req);if(!Number.isInteger(b.daily_minutes)||b.daily_minutes<5||b.daily_minutes>180)return fail(res,400,"STUDENT_INVALID_DAILY_MINUTES","daily_minutes must be 5..180",id);return ok(res,store.addConfig(m[1],b),id);}
m=u.pathname.match(/^\/api\/v1\/students\/([^/]+)\/academic-history$/);if(req.method==="POST"&&m){const uid=req.headers["x-user-id"];if(!store.owns(String(uid),m[1]))return fail(res,403,"STUDENT_FORBIDDEN","student is not bound to user",id);const b=await readJson(req);if(!b.stage||!Number.isInteger(b.grade)||!b.effective_from)return fail(res,400,"STUDENT_ACADEMIC_INVALID","stage, grade and effective_from are required",id);return ok(res,store.addAcademic(m[1],b),id,201);}
m=u.pathname.match(/^\/api\/v1\/students\/([^/]+)\/curriculum-position$/);if(req.method==="POST"&&m){const uid=String(req.headers["x-user-id"]||"");if(!store.owns(uid,m[1]))return fail(res,403,"STUDENT_FORBIDDEN","student is not bound to user",id);const cached=idem.get(`curriculum:${m[1]}`,id);if(cached)return ok(res,cached,id,200);const b=await readJson(req);if(!b.unit_id&&!b.progress_note)return fail(res,400,"CURRICULUM_POSITION_REQUIRED","unit_id or progress_note is required",id);const x=store.setPosition(m[1],b);idem.put(`curriculum:${m[1]}`,id,x);return ok(res,x,id,201);}
return fail(res,404,"SYS_NOT_FOUND","Resource not found",id);}catch(e){return fail(res,e.status||500,e.code||"SYS_INTERNAL",e.status?e.message:"Internal server error",id,Boolean(e.status&&e.status>=500));}}}
