import {randomUUID} from "node:crypto";import {readJson,ok,fail} from "./http.js";import {MemoryStore} from "./store.js";import {IdempotencyStore} from "./idempotency.js";
export function createHandler(store=new MemoryStore(),idem=new IdempotencyStore(),researchHandler=null,learningRepo=null,dailyPlanHandler=null,diagnosticHandler=null,feedbackHandler=null,activeLearningHandler=null,wrongBookHandler=null,growthHandler=null){return async(req,res)=>{const id=String(req.headers["x-request-id"]||randomUUID());try{const u=new URL(req.url,"http://localhost");
if(growthHandler&&u.pathname.endsWith("/growth")){const handled=await growthHandler(req,res,u,id);if(handled!==false)return handled;}
if(wrongBookHandler&&u.pathname.endsWith("/wrong-book")){const handled=await wrongBookHandler(req,res,u,id);if(handled!==false)return handled;}
if(activeLearningHandler&&u.pathname.includes("/active-learning/")){const handled=await activeLearningHandler(req,res,u,id);if(handled!==false)return handled;}
if(feedbackHandler&&u.pathname.includes("/feedback/")){const handled=await feedbackHandler(req,res,u,id);if(handled!==false)return handled;}
if(diagnosticHandler&&(u.pathname.includes("/diagnostic")||u.pathname.endsWith("/onboarding"))){const handled=await diagnosticHandler(req,res,u,id);if(handled!==false)return handled;}
if(dailyPlanHandler&&u.pathname.includes("/daily-")){const handled=await dailyPlanHandler(req,res,u,id);if(handled!==false)return handled;}
if(researchHandler&&u.pathname.startsWith("/api/v1/research/")){const handled=await researchHandler(req,res,u,id);if(handled!==false)return handled;}
if(req.method==="GET"&&u.pathname==="/health")return ok(res,{status:"ok",service:"smart-english-api"},id);
if(req.method==="GET"&&u.pathname==="/health/ready"){if(typeof store.health==="function")await store.health();return ok(res,{status:"ready"},id);}
if(req.method==="POST"&&u.pathname==="/api/v1/auth/wechat/login"){const b=await readJson(req);if(!b.open_id)return fail(res,400,"AUTH_OPEN_ID_REQUIRED","open_id is required",id);const z=await store.loginWechat(String(b.open_id));return ok(res,{user_id:z.user_id,status:z.status},id);}
if(req.method==="GET"&&u.pathname==="/api/v1/curriculum/textbooks")return ok(res,await store.listTextbooks(Object.fromEntries(u.searchParams)),id);
let m=u.pathname.match(/^\/api\/v1\/curriculum\/textbooks\/([^/]+)\/structure$/);if(req.method==="GET"&&m){const z=await store.getStructure(m[1]);return z?ok(res,z,id):fail(res,404,"CURRICULUM_TEXTBOOK_NOT_FOUND","textbook not found",id);}
if(req.method==="POST"&&u.pathname==="/api/v1/students"){const b=await readJson(req),uid=req.headers["x-user-id"];if(!uid)return fail(res,401,"AUTH_REQUIRED","x-user-id is required",id);if(!b.display_name||!b.current_stage||!Number.isInteger(b.current_grade))return fail(res,400,"STUDENT_INVALID_INPUT","display_name, current_stage and integer current_grade are required",id);if(!["Primary","Middle","High"].includes(b.current_stage)||b.current_grade<1||b.current_grade>12)return fail(res,400,"STUDENT_INVALID_GRADE","invalid stage or grade",id);return ok(res,await store.createStudent(String(uid),b),id,201);}
m=u.pathname.match(/^\/api\/v1\/students\/([^/]+)\/config$/);if(req.method==="PATCH"&&m){const uid=req.headers["x-user-id"];if(!await store.owns(String(uid),m[1]))return fail(res,403,"STUDENT_FORBIDDEN","student is not bound to user",id);const b=await readJson(req);if(!Number.isInteger(b.daily_minutes)||b.daily_minutes<5||b.daily_minutes>180)return fail(res,400,"STUDENT_INVALID_DAILY_MINUTES","daily_minutes must be 5..180",id);return ok(res,await store.addConfig(m[1],b),id);}
m=u.pathname.match(/^\/api\/v1\/students\/([^/]+)\/academic-history$/);if(req.method==="POST"&&m){const uid=req.headers["x-user-id"];if(!await store.owns(String(uid),m[1]))return fail(res,403,"STUDENT_FORBIDDEN","student is not bound to user",id);const b=await readJson(req);if(!b.stage||!Number.isInteger(b.grade)||!b.effective_from)return fail(res,400,"STUDENT_ACADEMIC_INVALID","stage, grade and effective_from are required",id);return ok(res,await store.addAcademic(m[1],b),id,201);}
m=u.pathname.match(/^\/api\/v1\/students\/([^/]+)\/curriculum-position$/);if(req.method==="POST"&&m){const uid=String(req.headers["x-user-id"]||"");if(!await store.owns(uid,m[1]))return fail(res,403,"STUDENT_FORBIDDEN","student is not bound to user",id);const idemKey=String(req.headers["idempotency-key"]||"");if(!idemKey)return fail(res,400,"IDEMPOTENCY_KEY_REQUIRED","Idempotency-Key is required",id);const scope=`curriculum:${m[1]}`,cached=await idem.get(scope,idemKey);if(cached)return ok(res,cached,id,200);const b=await readJson(req);if(!b.unit_id&&!b.progress_note)return fail(res,400,"CURRICULUM_POSITION_REQUIRED","unit_id or progress_note is required",id);const z=await store.setPosition(m[1],b);await idem.put(scope,idemKey,z);return ok(res,z,id,201);}
m=u.pathname.match(/^\/api\/v1\/students\/([^/]+)\/learning-sessions$/);if(req.method==="POST"&&m&&learningRepo){const uid=String(req.headers["x-user-id"]||"");if(!await store.owns(uid,m[1]))return fail(res,403,"STUDENT_FORBIDDEN","student is not bound to user",id);return ok(res,await learningRepo.startSession(m[1],await readJson(req)),id,201);}
m=u.pathname.match(/^\/api\/v1\/students\/([^/]+)\/learning-events$/);if(req.method==="POST"&&m&&learningRepo){const uid=String(req.headers["x-user-id"]||"");if(!await store.owns(uid,m[1]))return fail(res,403,"STUDENT_FORBIDDEN","student is not bound to user",id);const b=await readJson(req);if(!b.event_type)return fail(res,400,"LEARNING_EVENT_TYPE_REQUIRED","event_type is required",id);return ok(res,await learningRepo.appendEvent(m[1],b),id,201);}
m=u.pathname.match(/^\/api\/v1\/students\/([^/]+)\/learning-sessions\/([^/]+)\/complete$/);if(req.method==="POST"&&m&&learningRepo){const uid=String(req.headers["x-user-id"]||"");if(!await store.owns(uid,m[1]))return fail(res,403,"STUDENT_FORBIDDEN","student is not bound to user",id);const z=await learningRepo.endSession(m[1],m[2],await readJson(req));return z?ok(res,z,id):fail(res,409,"LEARNING_SESSION_NOT_ACTIVE","session not active",id);}
m=u.pathname.match(/^\/api\/v1\/students\/([^/]+)\/attempts$/);if(req.method==="POST"&&m&&learningRepo){const uid=String(req.headers["x-user-id"]||"");if(!await store.owns(uid,m[1]))return fail(res,403,"STUDENT_FORBIDDEN","student is not bound to user",id);const key=String(req.headers["idempotency-key"]||"");if(!key)return fail(res,400,"IDEMPOTENCY_KEY_REQUIRED","Idempotency-Key is required",id);const b=await readJson(req);if(!b.content_version_id||!b.answer_payload||!b.result)return fail(res,400,"ATTEMPT_INVALID_INPUT","content_version_id, answer_payload and result are required",id);const z=await learningRepo.createAttempt(m[1],{...b,request_id:key});return ok(res,z,id,201);}
return fail(res,404,"SYS_NOT_FOUND","Resource not found",id);}catch(e){return fail(res,e.status||500,e.code||"SYS_INTERNAL",e.status?e.message:"Internal server error",id,Boolean(!e.status||e.status>=500));}}}
