import {readJson,ok,fail} from "./http.js";
export function createDiagnosticHttpHandler({store,idem,onboardingService,sessionService,selector,learningRepo,estimateUpdater,completionOrchestrator}){return async(req,res,u,requestId)=>{let m=u.pathname.match(/^\/api\/v1\/students\/([^/]+)\/onboarding$/);if(req.method==="POST"&&m){if(!await owns(req,store,m[1]))return fail(res,403,"STUDENT_FORBIDDEN","student is not bound to user",requestId);const key=requireIdem(req,res,requestId);if(!key)return;const scope=`onboarding:${m[1]}`,body=await readJson(req),r=await idem.run(scope,key,()=>onboardingService.complete(m[1],body),201);return ok(res,r.value,requestId,r.reused?200:201);}
 m=u.pathname.match(/^\/api\/v1\/students\/([^/]+)\/diagnostic\/start$/);if(req.method==="POST"&&m){if(!await owns(req,store,m[1]))return fail(res,403,"STUDENT_FORBIDDEN","student is not bound to user",requestId);const b=await readJson(req);return ok(res,await sessionService.start(m[1],b.onboarding_profile_id??null),requestId,201);}
 m=u.pathname.match(/^\/api\/v1\/students\/([^/]+)\/diagnostic\/([^/]+)\/next$/);if(req.method==="GET"&&m){if(!await owns(req,store,m[1]))return fail(res,403,"STUDENT_FORBIDDEN","student is not bound to user",requestId);if(!await sessionOwned(store,m[1],m[2]))return fail(res,404,"DIAGNOSTIC_SESSION_NOT_FOUND","diagnostic session not found",requestId);return ok(res,await selector.next(m[2]),requestId);}
 m=u.pathname.match(/^\/api\/v1\/students\/([^/]+)\/diagnostic\/([^/]+)\/answer$/);if(req.method==="POST"&&m){if(!await owns(req,store,m[1]))return fail(res,403,"STUDENT_FORBIDDEN","student is not bound to user",requestId);if(!await sessionOwned(store,m[1],m[2]))return fail(res,404,"DIAGNOSTIC_SESSION_NOT_FOUND","diagnostic session not found",requestId);const key=String(req.headers["idempotency-key"]||"");if(!key)return fail(res,400,"IDEMPOTENCY_KEY_REQUIRED","Idempotency-Key is required",requestId);const b=await readJson(req);if(!b.diagnostic_item_id||!b.content_version_id||!b.answer_payload||!b.result)return fail(res,400,"DIAGNOSTIC_ANSWER_INVALID","diagnostic_item_id, content_version_id, answer_payload and result are required",requestId);const attempt=await learningRepo.createAttempt(m[1],{...b,request_id:key});const estimate=await estimateUpdater.applyAttempt(m[2],b.diagnostic_item_id,attempt.attempt_id);return ok(res,{attempt,estimate},requestId,201);}
 m=u.pathname.match(/^\/api\/v1\/students\/([^/]+)\/diagnostic\/([^/]+)\/status$/);if(req.method==="GET"&&m){if(!await owns(req,store,m[1]))return fail(res,403,"STUDENT_FORBIDDEN","student is not bound to user",requestId);const z=(await store.pool.query("SELECT * FROM diagnostic_sessions WHERE diagnostic_session_id=$1 AND student_id=$2",[m[2],m[1]])).rows[0];return z?ok(res,z,requestId):fail(res,404,"DIAGNOSTIC_SESSION_NOT_FOUND","diagnostic session not found",requestId);}
 m=u.pathname.match(/^\/api\/v1\/students\/([^/]+)\/diagnostic\/([^/]+)\/finalize$/);if(req.method==="POST"&&m){if(!await owns(req,store,m[1]))return fail(res,403,"STUDENT_FORBIDDEN","student is not bound to user",requestId);if(!await sessionOwned(store,m[1],m[2]))return fail(res,404,"DIAGNOSTIC_SESSION_NOT_FOUND","diagnostic session not found",requestId);const key=requireIdem(req,res,requestId);if(!key)return;const scope=`diagnostic-finalize:${m[2]}`,r=await idem.run(scope,key,()=>completionOrchestrator.finalizeIfReady(m[2]),200);return ok(res,r.value,requestId);}
 return false;};}
async function owns(req,store,studentId){return store.owns(String(req.headers["x-user-id"]||""),studentId);}
async function sessionOwned(store,studentId,sessionId){return Boolean((await store.pool.query("SELECT 1 FROM diagnostic_sessions WHERE diagnostic_session_id=$1 AND student_id=$2",[sessionId,studentId])).rowCount);}

function requireIdem(req,res,requestId){const key=String(req.headers["idempotency-key"]||"");if(!key){fail(res,400,"IDEMPOTENCY_KEY_REQUIRED","Idempotency-Key is required",requestId);return null;}return key;}
