import {readJson,ok,fail} from "./http.js";
export function createFeedbackHttpHandler({store,idem,feedback}){return async(req,res,u,id)=>{let m=u.pathname.match(/^\/api\/v1\/students\/([^/]+)\/feedback\/attempts\/([^/]+)$/);if(req.method==="POST"&&m){if(!await owns(req,store,m[1]))return fail(res,403,"STUDENT_FORBIDDEN","student is not bound to user",id);if(!await attemptOwned(store,m[1],m[2]))return fail(res,404,"ATTEMPT_NOT_FOUND","attempt not found",id);const key=idempotencyKey(req);if(!key)return fail(res,400,"IDEMPOTENCY_KEY_REQUIRED","Idempotency-Key header is required",id);const out=await idem.run(`feedback:observe:${m[1]}:${m[2]}`,key,async()=>({feedback:await feedback.observeAttempt(m[2])}),201);return ok(res,out.value,id,201);}
m=u.pathname.match(/^\/api\/v1\/students\/([^/]+)\/feedback\/causes\/([^/]+)\/verify$/);if(req.method==="POST"&&m){if(!await owns(req,store,m[1]))return fail(res,403,"STUDENT_FORBIDDEN","student is not bound to user",id);if(!await causeOwned(store,m[1],m[2]))return fail(res,404,"ERROR_CAUSE_NOT_FOUND","error cause not found",id);const key=idempotencyKey(req);if(!key)return fail(res,400,"IDEMPOTENCY_KEY_REQUIRED","Idempotency-Key header is required",id);const b=await readJson(req);if(!b.verification_type||!b.result)return fail(res,400,"VERIFICATION_INVALID_INPUT","verification_type and result are required",id);const out=await idem.run(`feedback:verify:${m[1]}:${m[2]}`,key,()=>feedback.verifyAndPlan(m[2],b),200);return ok(res,out.value,id);}
m=u.pathname.match(/^\/api\/v1\/students\/([^/]+)\/feedback\/repairs\/([^/]+)\/complete$/);if(req.method==="POST"&&m){if(!await owns(req,store,m[1]))return fail(res,403,"STUDENT_FORBIDDEN","student is not bound to user",id);const key=idempotencyKey(req);if(!key)return fail(res,400,"IDEMPOTENCY_KEY_REQUIRED","Idempotency-Key header is required",id);const b=await readJson(req);const out=await idem.run(`feedback:complete:${m[1]}:${m[2]}`,key,()=>feedback.completeRepair(m[1],m[2],{planDate:b.plan_date??null}),200);return ok(res,out.value,id);}
return false;};}
async function owns(req,store,studentId){return store.owns(String(req.headers["x-user-id"]||""),studentId);}
async function attemptOwned(store,studentId,attemptId){return Boolean((await store.pool.query("SELECT 1 FROM question_attempts WHERE attempt_id=$1 AND student_id=$2",[attemptId,studentId])).rowCount);}
async function causeOwned(store,studentId,hypothesisId){return Boolean((await store.pool.query("SELECT 1 FROM error_cause_hypotheses h JOIN error_observations o USING(error_observation_id) WHERE h.error_cause_hypothesis_id=$1 AND o.student_id=$2",[hypothesisId,studentId])).rowCount);}

function idempotencyKey(req){const v=req.headers['idempotency-key'];return typeof v==='string'&&v.trim()?v.trim():null;}
