import http from "node:http";import {createHandler} from "./app.js";import {createPool} from "./db.js";import {PostgresStore} from "./repositories/postgres.js";import {PostgresIdempotencyStore} from "./idempotency-postgres.js";import {ResearchPostgresRepository} from "./repositories/research-postgres.js";import {createResearchHandler} from "./research-routes.js";import {LearningPostgresRepository} from "./repositories/learning-postgres.js";import {ReviewPlanner} from "./review-planner.js";import {CandidateBuilder} from "./candidate-builder.js";import {SchedulerPolicyService} from "./scheduler-policy.js";import {DailyScheduler} from "./daily-scheduler.js";import {ReplanService} from "./replan-service.js";import {DailyPlanOrchestrator} from "./daily-plan-orchestrator.js";import {DailyPlanProgressService} from "./daily-plan-progress.js";import {createDailyPlanHandler} from "./daily-plan-routes.js";import {OnboardingService} from "./onboarding-service.js";import {DiagnosticPolicyService,DiagnosticSessionService} from "./diagnostic-service.js";import {DiagnosticSelector} from "./diagnostic-selector.js";import {DiagnosticEstimateUpdater} from "./diagnostic-estimate-updater.js";import {DiagnosticCalibrationService} from "./diagnostic-calibration.js";import {DiagnosticCompletionOrchestrator} from "./diagnostic-completion-orchestrator.js";import {createDiagnosticHttpHandler} from "./diagnostic-http.js";import {ErrorObservationService} from "./error-observation-service.js";import {ErrorCauseHypothesisService} from "./error-cause-hypothesis-service.js";import {ErrorCauseVerificationService} from "./error-cause-verification-service.js";import {MicroRepairPlanner} from "./micro-repair-planner.js";import {MicroRepairCompletionService} from "./micro-repair-completion-service.js";import {FeedbackOrchestrator} from "./feedback-orchestrator.js";import {createFeedbackHttpHandler} from "./feedback-http.js";
const port=Number(process.env.PORT||3000),pool=createPool(),store=new PostgresStore(pool),idem=new PostgresIdempotencyStore(pool),researchRepo=new ResearchPostgresRepository(pool),learningRepo=new LearningPostgresRepository(pool);
const reviewPlanner=new ReviewPlanner(pool),candidateBuilder=new CandidateBuilder(pool,{reviewPlanner}),policyService=new SchedulerPolicyService(pool),scheduler=new DailyScheduler(pool,{policyService}),replanService=new ReplanService(pool,scheduler),orchestrator=new DailyPlanOrchestrator({pool,candidateBuilder,policyService,scheduler,replanService}),progress=new DailyPlanProgressService(pool),dailyPlanHandler=createDailyPlanHandler({store,orchestrator,progress});
const onboardingService=new OnboardingService(pool),diagnosticPolicyService=new DiagnosticPolicyService(pool),diagnosticSessionService=new DiagnosticSessionService(pool,diagnosticPolicyService),diagnosticSelector=new DiagnosticSelector(pool),diagnosticEstimateUpdater=new DiagnosticEstimateUpdater(pool),diagnosticCalibrationService=new DiagnosticCalibrationService(pool),diagnosticCompletionOrchestrator=new DiagnosticCompletionOrchestrator({pool,selector:diagnosticSelector,sessionService:diagnosticSessionService,calibrationService:diagnosticCalibrationService,dailyPlanOrchestrator:orchestrator}),diagnosticHandler=createDiagnosticHttpHandler({store,idem,onboardingService,sessionService:diagnosticSessionService,selector:diagnosticSelector,learningRepo,estimateUpdater:diagnosticEstimateUpdater,completionOrchestrator:diagnosticCompletionOrchestrator});
const feedback=new FeedbackOrchestrator({observations:new ErrorObservationService(pool),hypotheses:new ErrorCauseHypothesisService(pool),verifications:new ErrorCauseVerificationService(pool),repairs:new MicroRepairPlanner(pool),completion:new MicroRepairCompletionService(pool,{dailyPlanProgress:progress})}),feedbackHandler=createFeedbackHttpHandler({store,feedback});
const server=http.createServer(createHandler(store,idem,createResearchHandler(researchRepo),learningRepo,dailyPlanHandler,diagnosticHandler,feedbackHandler));
server.listen(port,()=>console.log(`smart-english-api listening on :${port}`));
async function shutdown(){server.close(async()=>{await pool.end();process.exit(0);});}
process.on("SIGTERM",shutdown);process.on("SIGINT",shutdown);
