import test from "node:test";import assert from "node:assert/strict";import http from "node:http";import pg from "pg";import {createHandler} from "../src/app.js";import {PostgresStore} from "../src/repositories/postgres.js";import {LearningPostgresRepository} from "../src/repositories/learning-postgres.js";import {OnboardingService} from "../src/onboarding-service.js";import {DiagnosticPolicyService,DiagnosticSessionService} from "../src/diagnostic-service.js";import {DiagnosticSelector} from "../src/diagnostic-selector.js";import {DiagnosticEstimateUpdater} from "../src/diagnostic-estimate-updater.js";import {createDiagnosticHttpHandler} from "../src/diagnostic-http.js";import {DiagnosticCalibrationService} from "../src/diagnostic-calibration.js";import {DiagnosticCompletionOrchestrator} from "../src/diagnostic-completion-orchestrator.js";import {ReviewPlanner} from "../src/review-planner.js";import {CandidateBuilder} from "../src/candidate-builder.js";import {SchedulerPolicyService} from "../src/scheduler-policy.js";import {DailyScheduler} from "../src/daily-scheduler.js";import {ReplanService} from "../src/replan-service.js";import {DailyPlanOrchestrator} from "../src/daily-plan-orchestrator.js";
async function setup(){const pool=new pg.Pool({connectionString:process.env.TEST_DATABASE_URL}),store=new PostgresStore(pool),learningRepo=new LearningPostgresRepository(pool),policy=new DiagnosticPolicyService(pool),sessions=new DiagnosticSessionService(pool,policy),selector=new DiagnosticSelector(pool),updater=new DiagnosticEstimateUpdater(pool),reviewPlanner=new ReviewPlanner(pool),candidateBuilder=new CandidateBuilder(pool,{reviewPlanner}),schedulerPolicy=new SchedulerPolicyService(pool),scheduler=new DailyScheduler(pool,{policyService:schedulerPolicy}),replan=new ReplanService(pool,scheduler),daily=new DailyPlanOrchestrator({pool,candidateBuilder,policyService:schedulerPolicy,scheduler,replanService:replan}),completion=new DiagnosticCompletionOrchestrator({pool,selector,sessionService:sessions,calibrationService:new DiagnosticCalibrationService(pool),dailyPlanOrchestrator:daily}),handler=createDiagnosticHttpHandler({store,onboardingService:new OnboardingService(pool),sessionService:sessions,selector,learningRepo,estimateUpdater:updater,completionOrchestrator:completion}),server=http.createServer(createHandler(store,undefined,null,learningRepo,null,handler));await new Promise(r=>server.listen(0,r));return{pool,store,server,base:`http://127.0.0.1:${server.address().port}`};}
async function student(base,open){let r=await fetch(base+"/api/v1/auth/wechat/login",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({open_id:open})}),b=await r.json(),uid=b.data.user_id;r=await fetch(base+"/api/v1/students",{method:"POST",headers:{"content-type":"application/json","x-user-id":uid},body:'{"display_name":"Diagnostic HTTP","current_stage":"Primary","current_grade":5}'});b=await r.json();return{uid,sid:b.data.student_id};}
test("diagnostic HTTP onboarding start next answer status with auth and idempotency",async()=>{const{pool,server,base}=await setup();try{const owner=await student(base,"diag-http-owner-"+crypto.randomUUID()),other=await student(base,"diag-http-other-"+crypto.randomUUID());let r=await fetch(base+`/api/v1/students/${owner.sid}/onboarding`,{method:"POST",headers:{"content-type":"application/json","x-user-id":owner.uid},body:'{"primary_goal":"SchoolSync","daily_minutes":20}'});assert.equal(r.status,201);let b=await r.json();const profile=b.data.profile;assert.equal(profile.daily_minutes,20);
 const ability=(await pool.query("INSERT INTO abilities(domain,code,name,stage_min,stage_max) VALUES('Vocabulary',$1,'HTTP diagnostic','Primary','Middle') RETURNING ability_id",["HTTP-"+crypto.randomUUID()])).rows[0],ci=(await pool.query("INSERT INTO content_items(content_type,source_type,status) VALUES('Choice','Research','Draft') RETURNING content_id")).rows[0],cv=(await pool.query("INSERT INTO content_versions(content_id,version_no,payload,difficulty_label,review_status,published_at) VALUES($1,1,$2,'Q3','Approved',now()) RETURNING content_version_id",[ci.content_id,{stem:"http diagnostic"}])).rows[0];await pool.query("UPDATE content_items SET current_version_id=$2,status='Published' WHERE content_id=$1",[ci.content_id,cv.content_version_id]);await pool.query("INSERT INTO content_ability(content_version_id,ability_id,weight,purpose) VALUES($1,$2,1,'Diagnostic')",[cv.content_version_id,ability.ability_id]);
 r=await fetch(base+`/api/v1/students/${owner.sid}/diagnostic/start`,{method:"POST",headers:{"content-type":"application/json","x-user-id":owner.uid},body:JSON.stringify({onboarding_profile_id:profile.onboarding_profile_id})});assert.equal(r.status,201);b=await r.json();const session=b.data.session,sessionId=session.diagnostic_session_id;
 r=await fetch(base+`/api/v1/students/${owner.sid}/diagnostic/${sessionId}/next`,{headers:{"x-user-id":other.uid}});assert.equal(r.status,403);
 r=await fetch(base+`/api/v1/students/${owner.sid}/diagnostic/${sessionId}/next`,{headers:{"x-user-id":owner.uid}});assert.equal(r.status,200);b=await r.json();const item=b.data.item;
 const body={diagnostic_item_id:item.diagnostic_item_id,content_version_id:item.content_version_id,answer_payload:{choice:"A"},result:"Correct",technical_status:"OK"};
 r=await fetch(base+`/api/v1/students/${owner.sid}/diagnostic/${sessionId}/answer`,{method:"POST",headers:{"content-type":"application/json","x-user-id":owner.uid},body:JSON.stringify(body)});assert.equal(r.status,400);b=await r.json();assert.equal(b.error.code,"IDEMPOTENCY_KEY_REQUIRED");
 const headers={"content-type":"application/json","x-user-id":owner.uid,"idempotency-key":"diag-answer-"+crypto.randomUUID()};r=await fetch(base+`/api/v1/students/${owner.sid}/diagnostic/${sessionId}/answer`,{method:"POST",headers,body:JSON.stringify(body)});assert.equal(r.status,201);b=await r.json();const firstAttempt=b.data.attempt.attempt_id;
 r=await fetch(base+`/api/v1/students/${owner.sid}/diagnostic/${sessionId}/answer`,{method:"POST",headers,body:JSON.stringify(body)});assert.equal(r.status,201);b=await r.json();assert.equal(b.data.attempt.attempt_id,firstAttempt);assert.equal(b.data.estimate.reason,"ALREADY_APPLIED");
 r=await fetch(base+`/api/v1/students/${owner.sid}/diagnostic/${sessionId}/status`,{headers:{"x-user-id":owner.uid}});assert.equal(r.status,200);b=await r.json();assert.equal(b.data.diagnostic_session_id,sessionId);
 await pool.query("UPDATE diagnostic_policies SET stop_rules=jsonb_set(stop_rules,'{max_items}','1'::jsonb) WHERE policy_key=$1 AND version=$2",[session.policy_key,session.policy_version]);
 r=await fetch(base+`/api/v1/students/${owner.sid}/diagnostic/${sessionId}/finalize`,{method:"POST",headers:{"x-user-id":owner.uid}});assert.equal(r.status,200);b=await r.json();assert.equal(b.data.completed,true);assert.equal(b.data.session.status,"Completed");const planId=b.data.daily_plan.plan.daily_plan_id;assert.ok(planId);
 r=await fetch(base+`/api/v1/students/${owner.sid}/diagnostic/${sessionId}/finalize`,{method:"POST",headers:{"x-user-id":owner.uid}});assert.equal(r.status,200);b=await r.json();assert.equal(b.data.reused,true);assert.equal(b.data.daily_plan.plan.daily_plan_id,planId);
 const plans=(await pool.query("SELECT daily_plan_id,status FROM daily_plans WHERE student_id=$1 AND plan_date=CURRENT_DATE",[owner.sid])).rows;assert.equal(plans.length,1);assert.equal(plans[0].status,"Active");
 }finally{await new Promise(r=>server.close(r));await pool.end();}});
