import test from "node:test";import assert from "node:assert/strict";import pg from "pg";import {OutboxWorker} from "../src/outbox-worker.js";const it=process.env.TEST_DATABASE_URL?test:test.skip;
class FixtureWorker extends OutboxWorker{
 constructor(pool,builder,eventId,options={}){super(pool,builder,options);this.eventId=eventId}
 async claimOne(){const token=crypto.randomUUID();return(await this.pool.query("UPDATE outbox_events SET claimed_at=now(),claim_token=$2,attempt_count=attempt_count+1 WHERE event_id=$1 AND processed_at IS NULL AND dead_lettered_at IS NULL AND available_at<=now() AND (claim_token IS NULL OR claimed_at<now()-($3::int*interval '1 second')) RETURNING *",[this.eventId,token,this.leaseSeconds])).rows[0]??null}
}

async function event(p,name){return(await p.query("INSERT INTO outbox_events(aggregate_type,aggregate_id,event_type,payload) VALUES('QuestionAttempt',gen_random_uuid(),'AttemptRecorded',$1) RETURNING event_id",[{test_name:"S9-"+name+"-"+crypto.randomUUID()}])).rows[0];}
it("outbox applies bounded exponential retry and dead letters poison events",async()=>{const p=new pg.Pool({connectionString:process.env.TEST_DATABASE_URL});try{const e=await event(p,"poison"),bad={buildForAttempt:async()=>{throw new Error("poison")}},w=new FixtureWorker(p,bad,e.event_id,{maxAttempts:3,baseBackoffSeconds:2,maxBackoffSeconds:3});let r=await w.processOne();assert.equal(r.status,"Retry");assert.equal(r.retry_after_seconds,2);await p.query("UPDATE outbox_events SET available_at=now() WHERE event_id=$1",[e.event_id]);r=await w.processOne();assert.equal(r.status,"Retry");assert.equal(r.retry_after_seconds,3);await p.query("UPDATE outbox_events SET available_at=now() WHERE event_id=$1",[e.event_id]);r=await w.processOne();assert.equal(r.status,"DeadLetter");const row=(await p.query("SELECT attempt_count,dead_lettered_at,dead_letter_reason FROM outbox_events WHERE event_id=$1",[e.event_id])).rows[0];assert.equal(row.attempt_count,3);assert.ok(row.dead_lettered_at);assert.match(row.dead_letter_reason,/poison/);assert.equal(await w.claimOne(),null);}finally{await p.end();}});
it("dead letter does not starve a fresh event",async()=>{const p=new pg.Pool({connectionString:process.env.TEST_DATABASE_URL});try{const dead=await event(p,"dead");await p.query("UPDATE outbox_events SET dead_lettered_at=now(),attempt_count=8 WHERE event_id=$1",[dead.event_id]);const fresh=await event(p,"fresh"),w=new FixtureWorker(p,{buildForAttempt:async()=>[]},fresh.event_id);const c=await w.claimOne();assert.equal(c.event_id,fresh.event_id);}finally{await p.end();}});
