import test from"node:test";import assert from"node:assert/strict";import pg from"pg";import{StudentTaskContentReadModel}from"../src/student-task-content-read-model.js";import{StudentAnswerService}from"../src/student-answer-service.js";import{LearningPostgresRepository}from"../src/repositories/learning-postgres.js";
const it=process.env.TEST_DATABASE_URL?test:test.skip;
it("serves and scores approved content for a current school-sync curriculum position",async()=>{const p=new pg.Pool({connectionString:process.env.TEST_DATABASE_URL});try{
 const reviewer=(await p.query("INSERT INTO users(status) VALUES('Active') RETURNING user_id")).rows[0],student=(await p.query("INSERT INTO students(display_name,current_stage,current_grade) VALUES('s11-school','Primary',5) RETURNING student_id")).rows[0];
 const book=(await p.query("INSERT INTO textbooks(publisher,stage,grade,status) VALUES('Synthetic','Primary',5,'Active') RETURNING textbook_id")).rows[0],unit=(await p.query("INSERT INTO units(textbook_id,unit_no,sort_order) VALUES($1,'U1',1) RETURNING unit_id",[book.textbook_id])).rows[0],pos=(await p.query("INSERT INTO curriculum_positions(student_id,textbook_id,unit_id,source,is_current) VALUES($1,$2,$3,'Manual',true) RETURNING position_id",[student.student_id,book.textbook_id,unit.unit_id])).rows[0];
 const k=(await p.query("INSERT INTO knowledge_points(level,domain,code,name) VALUES(1,'Grammar',$1,'synthetic school knowledge') RETURNING knowledge_id",["S11S-"+crypto.randomUUID()])).rows[0];await p.query("INSERT INTO curriculum_knowledge_mappings(textbook_id,unit_id,knowledge_id,source) VALUES($1,$2,$3,'Research')",[book.textbook_id,unit.unit_id,k.knowledge_id]);
 const plan=(await p.query("INSERT INTO daily_plans(student_id,plan_date,version,status,available_minutes,strategy_version) VALUES($1,'2026-10-07',1,'Active',20,'s11@1') RETURNING daily_plan_id",[student.student_id])).rows[0],task=(await p.query("INSERT INTO daily_tasks(daily_plan_id,source_type,target_type,target_id,estimated_seconds,priority,sort_order,reason_code,status) VALUES($1,'SchoolSync','CurriculumPosition',$2,180,100,1,'SCHOOL_SYNC','Pending') RETURNING daily_task_id",[plan.daily_plan_id,pos.position_id])).rows[0];
 const item=(await p.query("INSERT INTO content_items(content_type,source_type,status) VALUES('Choice','Research','Published') RETURNING content_id")).rows[0],v=(await p.query("INSERT INTO content_versions(content_id,version_no,payload,answer_payload,explanation_payload,review_status,reviewed_by,reviewed_at,published_at) VALUES($1,1,$2,$3,$4,'Approved',$5,now(),now()) RETURNING content_version_id",[item.content_id,{stem:"He ___ home.",options:["go","goes"]},{correct_index:1},{text:"Use goes."},reviewer.user_id])).rows[0];await p.query("UPDATE content_items SET current_version_id=$2 WHERE content_id=$1",[item.content_id,v.content_version_id]);await p.query("INSERT INTO content_knowledge(content_version_id,knowledge_id,role,weight,purpose,review_status) VALUES($1,$2,'PrimaryTested',1,'Learn','Approved')",[v.content_version_id,k.knowledge_id]);
 const view=await new StudentTaskContentReadModel(p).forTask(student.student_id,task.daily_task_id);assert.equal(view.content.content_version_id,v.content_version_id);assert.equal("answer_payload" in view.content,false);
 const answer=await new StudentAnswerService(p,new LearningPostgresRepository(p)).submit(student.student_id,{daily_task_id:task.daily_task_id,content_version_id:v.content_version_id,answer_payload:{choice_index:1}},"school-sync-answer");assert.equal(answer.result,"Correct");assert.equal(answer.explanation_payload.text,"Use goes.");
}finally{await p.end();}});
