import test from"node:test";import assert from"node:assert/strict";import pg from"pg";import{StudentAnswerService}from"../src/student-answer-service.js";import{LearningPostgresRepository}from"../src/repositories/learning-postgres.js";
const it=process.env.TEST_DATABASE_URL?test:test.skip;
it("rejects content mapped to another active task target",async()=>{const p=new pg.Pool({connectionString:process.env.TEST_DATABASE_URL});try{
 const reviewer=(await p.query("INSERT INTO users(status) VALUES('Active') RETURNING user_id")).rows[0],student=(await p.query("INSERT INTO students(display_name,current_stage,current_grade) VALUES('s11-answer','Primary',5) RETURNING student_id")).rows[0];
 const k1=(await p.query("INSERT INTO knowledge_points(level,domain,code,name) VALUES(1,'Grammar',$1,'k1') RETURNING knowledge_id",["S11A-"+crypto.randomUUID()])).rows[0],k2=(await p.query("INSERT INTO knowledge_points(level,domain,code,name) VALUES(1,'Grammar',$1,'k2') RETURNING knowledge_id",["S11B-"+crypto.randomUUID()])).rows[0];
 const plan=(await p.query("INSERT INTO daily_plans(student_id,plan_date,version,status,available_minutes,strategy_version) VALUES($1,'2026-10-07',1,'Active',20,'s11@1') RETURNING daily_plan_id",[student.student_id])).rows[0],task=(await p.query("INSERT INTO daily_tasks(daily_plan_id,source_type,target_type,target_id,estimated_seconds,priority,sort_order,reason_code,status) VALUES($1,'Review','Knowledge',$2,180,90,1,'DUE_REVIEW','Pending') RETURNING daily_task_id",[plan.daily_plan_id,k1.knowledge_id])).rows[0];
 const item=(await p.query("INSERT INTO content_items(content_type,source_type,status) VALUES('Choice','Research','Published') RETURNING content_id")).rows[0],v=(await p.query("INSERT INTO content_versions(content_id,version_no,payload,answer_payload,explanation_payload,review_status,reviewed_by,reviewed_at,published_at) VALUES($1,1,$2,$3,$4,'Approved',$5,now(),now()) RETURNING content_version_id",[item.content_id,{stem:"x",options:["a","b"]},{correct_index:1},{text:"why"},reviewer.user_id])).rows[0];
 await p.query("UPDATE content_items SET current_version_id=$2 WHERE content_id=$1",[item.content_id,v.content_version_id]);await p.query("INSERT INTO content_knowledge(content_version_id,knowledge_id,role,weight,purpose,review_status) VALUES($1,$2,'PrimaryTested',1,'Learn','Approved')",[v.content_version_id,k2.knowledge_id]);
 const svc=new StudentAnswerService(p,new LearningPostgresRepository(p));await assert.rejects(()=>svc.submit(student.student_id,{daily_task_id:task.daily_task_id,content_version_id:v.content_version_id,answer_payload:{choice_index:1}},"cross-task"),e=>e.code==="STUDENT_CONTENT_NOT_AVAILABLE"&&e.status===409);
 const count=await p.query("SELECT count(*)::int n FROM question_attempts WHERE student_id=$1 AND request_id='cross-task'",[student.student_id]);assert.equal(count.rows[0].n,0);
}finally{await p.end();}});
